# model
IMAGE_ORDERING_CHANNELS_LAST = "channels_last"
IMAGE_ORDERING_CHANNELS_FIRST = "channels_first"
IMAGE_ORDERING = IMAGE_ORDERING_CHANNELS_LAST


# train
INPUT_WIDTH = 240
INPUT_HEIGHT = 160
INPUT_CHANNEL = 3
EPOCHS = 1000
BATCH_SIZE = 8
STEPS_PER_EPOCH = 1000
VALIDATION_STEPS = 100
